name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Flask deps
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Test Flask app
        run: |
          cd backend
          python -m unittest || echo "(No tests yet)"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend deps & build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deployment Step (Manual for now)
        run: echo "Add Render + GitHub Pages deploy here."

